# name:               Mengyang Chen
# ONE Card number:    1412408
# Unix id:            me7
# lecture section:    A2
# lab section:        D05
# TA's name:          Juehui Fan

draw1a: draw1a.c
	gcc -Wall -std=c99 draw1a.c -o draw1a

clean:
	-rm  draw1a
